parkhawk/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('parkmap.urls'))
]

parkmap/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('submit-parking', views.parking_spot_create_view),
    path('about', views.about, name='about'),
    path('find-parking', views.ParkingListView.as_view(), name='findParking')
]

parkmap/models.py
from django.db import models

# Create your mode1s here.
class ParkingSpot(models.Model):
    address = models.CharField(max_length=140) # address
    latitude = models.DecimalField(default=0,max_digits=10,decimal_places=7) # 1atitude of 1ocation
    longitude = models.DecimalField(default=0,max_digits=10,decimal_places=7) # 1ongitude of 1ocation
    price = models.DecimalField(max_digits=5,decimal_places=2) # price of space
    hours_start_time = models.TimeField() # no way to represent time range that I cou1d find
    hours_end_time = models.TimeField()   # so making start hour and end hour separate
    note = models.CharField(max_length=500) # note for 1isting creator to 1eave for others

    def __str__(self):
        return "{0}\t{1}\t{2}\t{3}\t{4}\t{5}\t{6}".format(self.address, self.latitude, self.longitude, self.price, self.hours_start_time, self.hours_end_time, self.note)

parkmap/forms.py
from django.forms import ModelForm
from .models import ParkingSpot

class ParkingSpotForm(ModelForm):
    class Meta:
        model = ParkingSpot
        fields = ['address','latitude','longitude', 'price', 'hours_start_time', 'hours_end_time', 'note']
       

parkmap/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from .models import ParkingSpot
from .forms import ParkingSpotForm


# Create your views here.

def index(request):
    return render(request, 'parkmap/base.html')

def parking_spot_create_view(request):
    form = ParkingSpotForm(request.POST or None)
    if form.is_valid():
        form.save()
    
    context = {'form': form}

    return render(request, 'parkmap/form.html', context)


def about(request):
    return render(request, 'parkmap/about.html')

def findParking(request):
    return render(request, 'parkmap/findParking.html')

class ParkingListView(ListView):

    model = ParkingSpot

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

parkmap/templates/parkmap/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'parkmap/css/main_page.css' %}" type="text/css">

    <title>ParkHawk</title>
</head>

<header>

    {% include 'parkmap/includes/header.html' %}

</header>

<body>
    <div class="main-jumbotron"></div>
    <div class="jumbotron">

        <h1 class="display-4" style="color: #f8b500;">ParkHawk</h1>
        <p class="lead">ParkHawk is a tool that uses crowd-sourced data from people like you to help everyone find free and cheap parking around the University of Iowa and Iowa City!</p>
        <hr class="my-4">
        <p>The Iowa City area has a lot to offer, but sometimes it can be a bit of a struggle to get there</p>
        <a class="btn btn-primary btn-lg" href="/find-parking" role="button">Find Your Spot Now</a>
        </div>

    </div>

    <div class="jumbotron second-jumbotron">

        <h4>Parking can be a bit of a hassle in Iowa City</h4>
        <p>It's a great place, but finding somewhere to leave your car is difficult sometimes</p>

        <h5>With the power of crowdsourcing, the people of Iowa City can help each other find the most convenient places to park</h5>
        
        <h3 style="color: #f8b500">Make your community a better place today!</h3>
    </div>
    
</body>
</html>

parkmap/templates/parkmap/form.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'parkmap/css/parkingspot_list.css' %}" type="text/css" >
    <title>ParkHawk</title>
</head>

<header>

    {% include 'parkmap/includes/header.html' %}

</header>


<body>
    <div class="container">
    
        <form class="jumbotron" method="POST"> {% csrf_token %}

            {{ form|crispy }}

            <button class="btn btn-primary" type="submit">Submit</button>

        </form>
    </div>


    <script>
    
        let address = document.getElementById("id_address");
        let latElement = document.getElementById("id_latitude");
        let lngElement = document.getElementById("id_longitude");
        

        address.addEventListener("input", (e) => {

            let key = "AIzaSyBya_p_fSTqn0PExLuB8kIwxPzDYnDI9Mg";
            let staddress = address.value;
            let queryurl = "https://maps.googleapis.com/maps/api/geocode/json?address="+ staddress +"&key=" + key


            fetch(queryurl).then((res) => {
                return res.json();
            }).then((jsonres) => {
                let latitude = jsonres.results[0].geometry.location.lat;
                let longitude = jsonres.results[0].geometry.location.lng;

                latElement.value = latitude;
                lngElement.value = longitude;   
            });

        });
        
            

    </script>
</body>
</html>

parkmap/templates/parkmap/includes/header.html
{% block content %}

<div class="container-fluid nav-container" style="margin:0;" >
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" style="color: #f8b500;"  href="/">Parkhawk</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" href="/find-parking">Find Parking<span class="sr-only">(current)</span></a>
                </li>
                
                <li class="nav-item active">
                    <a class="nav-link" href="/submit-parking">Add Data<span class="sr-only">(current)</span></a>
                </li>
            </ul>

        </div>
    </nav>
</div>

{% endblock %}

parkmap/templates/parkmap/parkingspot_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'parkmap/css/parkingspot_list.css' %}" type="text/css" >
    <title>ParkHawk</title>
   
      
</head>

<header>

    {% include 'parkmap/includes/header.html' %}

</header>

<body>
    

    <div class="container-fluid">
        <div class="jumbotron">
            <h1 class="display-4">Find Parking Near You</h1>
            <div id="map"></div>
        </div>


        <h2>Parking Spots</h2>
        
        


        <div class="list-group">


            {% for spot in object_list %}

                <div class="list-group-item list-group-item-action flex-column align-items-start">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ spot.address }}</h5>
                        <small>${{ spot.price }}</small>
                    </div>
                    <p class="mb-1">{{ spot.note }}</p>
                    <small>{{ spot.hours_start_time }} - {{ spot.hours_end_time }}</small>
                </div>
            {% endfor %}
        </div>

    </div>

    {% block script %}
        <script>
            
            let locList = [];

            {% for spot in object_list %}

                locList.push({lat:{{ spot.latitude }}, lng: {{ spot.longitude }} });
            {% endfor %}

           
        
        </script>
    {% endblock %}
    <script src="{% static 'parkmap/js/map.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBya_p_fSTqn0PExLuB8kIwxPzDYnDI9Mg&callback=initMap"></script>
    
    


</body>
</html>